---
title: "PSTAT220A Homework 1"
author: "Jeremy Knox"
date: "9/26/2019"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```

1. Write a R function that returns the following dispersion measures:   
(a) Standard deviation;
(b) Mean absolute deviation $n^{-1} \sum_{i=1}^{n}\left|x_{i}-\overline{x}\right|$;
(c) Median absolute deviation $\operatorname{Median}\left|x_{i}-\operatorname{Median}(x)\right|$;
(d) Inter-quartile range.

```{r Problem 1}
# example data: 
x <- c(1, exp(1), sqrt(2), pi, 3.5) # x = {1, 2.718282, 1.414214, 3.141593, 3.5}

sd <- function(x){
  # return the standard deviation of a vector of numerical data
  # example: x <- c(10,2,4,5), sd(x) = 2.947457
  m = mean(x)
  n = length(x)
  standard_deviation = sqrt((sum((x - m)^2)) / n)
  return(standard_deviation)
}
print("sd_result:")
sd(x)

mad <- function(x){
  # return the mean absolute deviation of a vector of numerical data
  # example: x <- c(10,2,4,5), mad(x) = 2.375
  m = mean(x)
  n = length(x)
  mean_absolute_deviation = (n^-1)*(sum(abs(x - m)))
  return(mean_absolute_deviation)
}
mad_result <- mad(x)

median_ad <- function(x){
  # return the median absolute deviation of a vector of numerical data
  # example: x <- c(10,2,4,5), median_ad(x) = 2.25
  median = median(x)
  median_absolute_deviation = median(abs(x - m))
  return(median_absolute_deviation)
}
median_ad_result <- median_ad(x)

iqr <- function(x){
  # return the inter-quartile range of a vector of numerical data
  # example; 
  # odd case: x <- c(10,2,4,5,6), iqr(x) = 4
  # even case: x <- c(10,2,4,5), iqr(x) = 4.5
  n = length(x)
  x = sort(x) 
  if (n%%2 == 0){
    first_half = x[0:(n/2)]
    second_half = x[(n/2+1):n]
    q1 = median(first_half)
    q3 = median(second_half)
    return(q3 - q1)
  }
  else {
    first_half = x[0:(n/2+0.5)]
    second_half = x[(n/2+1.5):n]
    q1 = median(first_half)
    q3 = median(second_half)
    return(q3 - q1)
  }
  }
iqr_result <- iqr(x)
```




```{r Problem 2}
library(faraway)
data(pima)

eda.shape <- function(x) {
    par(mfrow=c(2,2))
    hist(x)
    boxplot(x)
    qqnorm(x)
    qqline(x)
    plot(density(x))
}

stdevs <- lapply(pima[c("pregnant","diastolic", "bmi", "age")], sd)
mads <- lapply(pima[c("pregnant","diastolic", "bmi", "age")], mad)
meadian_ads <- lapply(pima[c("pregnant","diastolic", "bmi", "age")], median_ad)
iqrs <- lapply(pima[c("pregnant","diastolic", "bmi", "age")], iqr)

eda.shape(pima$pregnant)
eda.shape(pima$diastolic)
eda.shape(pima$bmi)
eda.shape(pima$age)
```




```{r Problem 3}

precip <- c(0.77,1.20,3.00,1.62,2.81,2.48,1.74,0.47,3.09,1.31,
            1.87,0.96,0.81,1.43,1.51,0.32,1.18,1.89,1.20,3.37,
            2.10,0.59,1.35,0.90,1.95,2.20,0.52,0.81,4.75,2.05)

qq.shape <- function(x) {
    par(mfrow=c(2,2))
    qqnorm(x)
    qqline(x)
}

qq.shape(precip)
qq.shape(log(precip))
qq.shape(sqrt(precip))
```



```{r}
library(MASS)
library(fitdistrplus)

trans_fails <- c(4381,3953,2603,2320,1161,3286,6914,4007,3168,
                 2376,7498,3923,9460,4525,2168,1288,5085,2217,
                 6922,218,1309,1875,1023,1697,1038,3699,6142,
                 4732,3330,4159,2537,3814,2157,7683,5539,4839,
                 6052,2420,5556,309,1295,3266,6679,1711,5931)

fit_normal <- fitdistr(trans_fails, densfun="normal")
fit_ln <- fitdistr(trans_fails, densfun="lognormal")
fit_exp <- fitdistr(trans_fails, densfun="exponential")
fit_gamma <- fitdistr(log(trans_fails), densfun="gamma")

par(mfrow=c(2,2))
plot.legend <- c("Normal", "Lognormal", "Exponential", "Gamma")
denscomp(list(fit_normal), legendtext = plot.legend)

```

